### PR TITLE
Add AppBar with category filter & extend chat bubble width 

### PR DESCRIPTION
**Pull request by Jantzilla**
This PR addresses issue #82. It doesn't however add a navigation drawer to the app ( as mentioned in the original issue).

**Changes include:**
- Adding an AppBar
- Replacing the chat category spinner with an options menu
- Adding the app name & current chat category inside the AppBar
- Using the Android filter icon
- Extending chat bubble width

**After Changes**

shipr-update

### CODE REVIEW

**Comment by yhdesai** [comment]
It's perfect except one small issue
The message box seems to be a bit bigger than the screen
photo_2019-04-14_12-19-26

**Comment by Jantzilla** [comment]
@yhdesai I have made the necessary change. The results look good on all my devices & emulators. Let me know if there is anything else. Thanks for the feedback.

**Comment by yhdesai** [comment]
Thanks for the PR!

**Comment by Jantzilla** [comment]
> Thanks for the PR!

You're welcome!

**Pull request merged**
